[source]
language = "go"
root = "."
layer_match = "component"
exclude = ["dist/"]

[source.layer_dirs]
enterprise = "domain"
interface = "port"
application = "usecase"
framework = "adapter"

[types]
UUID = "string"
