use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::process;

use clap::Parser;
use plat_manifest::Manifest;

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

#[derive(Parser)]
#[command(name = "plat-deprules", about = "Generate linter dependency rules from plat manifest")]
struct Cli {
    /// Path to plat architecture manifest (JSON)
    manifest: String,

    /// Output format: depguard | eslint | matrix
    #[arg(short, long, default_value = "matrix")]
    format: String,

    /// Go module path (required for depguard format)
    #[arg(long)]
    module: Option<String>,

    /// Layer to directory mapping (repeatable), e.g. --layer-dir enterprise=domain
    #[arg(long = "layer-dir", value_name = "LAYER=DIR")]
    layer_dir: Vec<String>,
}

// ---------------------------------------------------------------------------
// DepPolicy
// ---------------------------------------------------------------------------

struct DepPolicy {
    layers: Vec<String>,
    allowed: BTreeMap<String, BTreeSet<String>>,
    forbidden: BTreeMap<String, BTreeSet<String>>,
}

fn build_policy(manifest: &Manifest) -> DepPolicy {
    let layers: Vec<String> = manifest.layers.iter().map(|l| l.name.clone()).collect();
    let all: BTreeSet<String> = layers.iter().cloned().collect();

    let mut allowed = BTreeMap::new();
    let mut forbidden = BTreeMap::new();

    for layer in &manifest.layers {
        let deps: BTreeSet<String> = layer.depends.iter().cloned().collect();
        allowed.insert(layer.name.clone(), deps.clone());

        let mut deny = all.clone();
        deny.remove(&layer.name);
        for d in &deps {
            deny.remove(d);
        }
        forbidden.insert(layer.name.clone(), deny);
    }

    DepPolicy { layers, allowed, forbidden }
}

// ---------------------------------------------------------------------------
// Layer-dir mapping
// ---------------------------------------------------------------------------

fn parse_layer_dirs(args: &[String]) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    for entry in args {
        if let Some((k, v)) = entry.split_once('=') {
            map.insert(k.to_string(), v.to_string());
        } else {
            eprintln!("warning: ignoring malformed --layer-dir value: {entry}");
        }
    }
    map
}

fn resolve_dir(layer: &str, mapping: &BTreeMap<String, String>) -> String {
    mapping.get(layer).cloned().unwrap_or_else(|| layer.to_string())
}

// ---------------------------------------------------------------------------
// matrix format
// ---------------------------------------------------------------------------

fn render_matrix(policy: &DepPolicy) -> String {
    let mut out = String::new();
    out.push_str("# Layer dependency matrix (generated by plat)\n");

    let abbrevs: Vec<String> = policy
        .layers
        .iter()
        .map(|n| {
            let chars: Vec<char> = n.chars().collect();
            chars.iter().take(3).collect::<String>()
        })
        .collect();

    // Find column width: max of layer name lengths and 5 (for "check")
    let label_width = policy.layers.iter().map(|n| n.len()).max().unwrap_or(0);
    let col_width = abbrevs.iter().map(|a| a.len()).max().unwrap_or(3).max(5);

    // Header comment
    out.push_str("# check = allowed, x = forbidden, . = self\n\n");

    // Column headers
    out.push_str(&" ".repeat(label_width + 1));
    for abbr in &abbrevs {
        out.push_str(&format!("{:>width$}", abbr, width = col_width + 1));
    }
    out.push('\n');

    // Rows
    for (i, layer) in policy.layers.iter().enumerate() {
        out.push_str(&format!("{:<width$}", layer, width = label_width + 1));
        for (j, other) in policy.layers.iter().enumerate() {
            let sym = if i == j {
                "."
            } else if policy
                .allowed
                .get(layer)
                .map_or(false, |a| a.contains(other))
            {
                "check"
            } else {
                "x"
            };
            out.push_str(&format!("{:>width$}", sym, width = col_width + 1));
        }
        out.push('\n');
    }

    out
}

// ---------------------------------------------------------------------------
// depguard format
// ---------------------------------------------------------------------------

fn render_depguard(
    policy: &DepPolicy,
    module: &str,
    dir_map: &BTreeMap<String, String>,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by plat — layer dependency rules\n");
    out.push_str("# Add to .golangci.yml under linters-settings.depguard\n");
    out.push_str("linters-settings:\n");
    out.push_str("  depguard:\n");
    out.push_str("    rules:\n");

    for layer in &policy.layers {
        let forbidden = match policy.forbidden.get(layer) {
            Some(f) if !f.is_empty() => f,
            _ => continue,
        };

        let pkg = resolve_dir(layer, dir_map);
        out.push_str(&format!("      {pkg}:\n"));
        out.push_str("        files:\n");
        out.push_str(&format!("          - \"**/{pkg}/**\"\n"));
        out.push_str("        deny:\n");

        for denied_layer in forbidden {
            let denied_pkg = resolve_dir(denied_layer, dir_map);
            out.push_str(&format!(
                "          - pkg: \"{module}/{denied_pkg}\"\n"
            ));
            out.push_str(&format!(
                "            msg: \"layer {layer} must not depend on {denied_layer}\"\n"
            ));
        }
    }

    out
}

// ---------------------------------------------------------------------------
// eslint format
// ---------------------------------------------------------------------------

fn render_eslint(
    policy: &DepPolicy,
    dir_map: &BTreeMap<String, String>,
) -> String {
    let mut rules = Vec::new();

    for layer in &policy.layers {
        let allowed = match policy.allowed.get(layer) {
            Some(a) => a,
            None => continue,
        };

        let from_dir = resolve_dir(layer, dir_map);
        let allow_dirs: Vec<String> = allowed.iter().map(|l| resolve_dir(l, dir_map)).collect();

        let allow_json: Vec<String> = allow_dirs.iter().map(|d| format!("\"{}\"", d)).collect();

        rules.push(format!(
            "        {{\n          \"from\": \"{from_dir}\",\n          \"allow\": [{}]\n        }}",
            allow_json.join(", ")
        ));
    }

    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"rules\": {\n");
    out.push_str("    \"boundaries/element-types\": [\"error\", {\n");
    out.push_str("      \"default\": \"disallow\",\n");
    out.push_str("      \"rules\": [\n");
    out.push_str(&rules.join(",\n"));
    out.push('\n');
    out.push_str("      ]\n");
    out.push_str("    }]\n");
    out.push_str("  }\n");
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

fn main() {
    let cli = Cli::parse();

    let content = fs::read_to_string(&cli.manifest).unwrap_or_else(|e| {
        eprintln!("error: cannot read {}: {e}", cli.manifest);
        process::exit(1);
    });

    let manifest: Manifest = serde_json::from_str(&content).unwrap_or_else(|e| {
        eprintln!("error: invalid manifest: {e}");
        process::exit(1);
    });

    let policy = build_policy(&manifest);
    let dir_map = parse_layer_dirs(&cli.layer_dir);

    let output = match cli.format.as_str() {
        "matrix" => render_matrix(&policy),
        "depguard" => {
            let module = cli.module.as_deref().unwrap_or_else(|| {
                eprintln!("error: --module is required for depguard format");
                process::exit(1);
            });
            render_depguard(&policy, module, &dir_map)
        }
        "eslint" => render_eslint(&policy, &dir_map),
        other => {
            eprintln!("error: unknown format: {other} (expected: matrix, depguard, eslint)");
            process::exit(1);
        }
    };

    print!("{output}");
}
