-- | Generate dependency restriction rules from layer definitions.
--
-- Produces import restriction configurations for:
-- - Go (depguard / import policy)
-- - TypeScript (eslint-plugin-import / boundaries)
-- - Rust (module visibility conventions)
--
-- Also generates a generic "allowed dependencies" manifest.
module Plat.Verify.DepRules
  ( DepPolicy (..)
  , depPolicy
  , renderGoDepGuard
  , renderEslintBoundaries
  , renderDepMatrix
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set

import Plat.Core.Types

----------------------------------------------------------------------
-- Dependency policy
----------------------------------------------------------------------

-- | For each layer: which other layers it may depend on.
data DepPolicy = DepPolicy
  { dpLayers  :: [Text]
  , dpAllowed :: Map.Map Text (Set.Set Text)  -- layer -> allowed deps
  } deriving stock (Show, Eq)

depPolicy :: Architecture -> DepPolicy
depPolicy arch = DepPolicy
  { dpLayers  = map layerName (archLayers arch)
  , dpAllowed = Map.fromList
      [ (layerName ly, Set.fromList (layerDeps ly))
      | ly <- archLayers arch
      ]
  }

-- | The inverse: for each layer, which layers are FORBIDDEN.
forbidden :: DepPolicy -> Map.Map Text (Set.Set Text)
forbidden dp =
  let all_ = Set.fromList (dpLayers dp)
  in Map.mapWithKey (\ly allowed ->
       Set.delete ly $ all_ `Set.difference` allowed
     ) (dpAllowed dp)

----------------------------------------------------------------------
-- Go: depguard-style config
----------------------------------------------------------------------

-- | Render Go dependency guard rules.
-- Output is a .golangci.yml fragment for depguard linter.
renderGoDepGuard :: Text -> Map.Map Text Text -> DepPolicy -> Text
renderGoDepGuard modPath layerPkgMap dp = T.unlines $
  [ "# Generated by plat — layer dependency rules"
  , "# Add to .golangci.yml under linters-settings.depguard"
  , "linters-settings:"
  , "  depguard:"
  , "    rules:"
  ] ++
  concatMap goRule (Map.toList (forbidden dp))
  where
    pkg ly = Map.findWithDefault ly ly layerPkgMap

    goRule (ly, denied) =
      [ "      " <> pkg ly <> ":"
      , "        files:"
      , "          - \"**/" <> pkg ly <> "/**\""
      , "        deny:"
      ] ++
      [ "          - pkg: \"" <> modPath <> "/" <> pkg d <> "\""
        <> "\n            msg: \"layer " <> ly <> " must not depend on " <> d <> "\""
      | d <- Set.toList denied
      ]

----------------------------------------------------------------------
-- TypeScript: eslint boundaries config
----------------------------------------------------------------------

-- | Render ESLint boundaries plugin config fragment.
renderEslintBoundaries :: Map.Map Text Text -> DepPolicy -> Text
renderEslintBoundaries layerDirMap dp = T.unlines $
  [ "// Generated by plat — layer dependency rules"
  , "// Add to eslint.config.js or .eslintrc"
  , "{"
  , "  \"rules\": {"
  , "    \"boundaries/element-types\": [\"error\", {"
  , "      \"default\": \"disallow\","
  , "      \"rules\": ["
  ] ++
  concatMap eslintRule (Map.toList (dpAllowed dp)) ++
  [ "      ]"
  , "    }]"
  , "  }"
  , "}"
  ]
  where
    dir ly = Map.findWithDefault ly ly layerDirMap

    eslintRule (ly, allowed) =
      [ "        {"
      , "          \"from\": \"" <> dir ly <> "\","
      , "          \"allow\": [" <> T.intercalate ", "
            (map (\a -> "\"" <> dir a <> "\"") (Set.toList allowed)) <> "]"
      , "        },"
      ]

----------------------------------------------------------------------
-- Generic: dependency matrix
----------------------------------------------------------------------

-- | Render a human-readable dependency matrix.
renderDepMatrix :: DepPolicy -> Text
renderDepMatrix dp = T.unlines $
  [ "# Layer dependency matrix (generated by plat)"
  , "# ✓ = allowed, ✗ = forbidden, · = self"
  , ""
  , header
  ] ++
  map row (dpLayers dp)
  where
    maxLen = maximum (0 : map T.length (dpLayers dp))
    pad t = t <> T.replicate (maxLen - T.length t + 1) " "

    header = pad "" <> T.intercalate " " (map (\l -> T.take 3 l <> " ") (dpLayers dp))

    row from = pad from <> T.intercalate " " (map (cell from) (dpLayers dp))

    cell from to
      | from == to = " ·  "
      | to `Set.member` Map.findWithDefault Set.empty from (dpAllowed dp) = " ✓  "
      | otherwise = " ✗  "
